//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGC.Group {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Game : global::System.Configuration.ApplicationSettingsBase {
        
        private static Game defaultInstance = ((Game)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Game())));
        
        public static Game Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Grupo 99")]
        public string Name {
            get {
                return ((string)(this["Name"]));
            }
            set {
                this["Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\Shaders\\")]
        public string ShadersDirectory {
            get {
                return ((string)(this["ShadersDirectory"]));
            }
            set {
                this["ShadersDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\Media\\")]
        public string MediaDirectory {
            get {
                return ((string)(this["MediaDirectory"]));
            }
            set {
                this["MediaDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D\'Angelo, Pablo Rodrigo - Virgili José María")]
        public string Category {
            get {
                return ((string)(this["Category"]));
            }
            set {
                this["Category"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plantas vs Zombies Tower Defense")]
        public string Description {
            get {
                return ((string)(this["Description"]));
            }
            set {
                this["Description"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\LogoTGC-TgcScene.xml")]
        public string MeshTgc {
            get {
                return ((string)(this["MeshTgc"]));
            }
            set {
                this["MeshTgc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Texturas\\HUD_Girasol.jpg")]
        public string TexturaHUDGirasol {
            get {
                return ((string)(this["TexturaHUDGirasol"]));
            }
            set {
                this["TexturaHUDGirasol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\BolaRaziel-TgcScene.xml")]
        public string MeshRaziel {
            get {
                return ((string)(this["MeshRaziel"]));
            }
            set {
                this["MeshRaziel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\cielo-TgcScene.xml")]
        public string MeshCielo {
            get {
                return ((string)(this["MeshCielo"]));
            }
            set {
                this["MeshCielo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\Girasol-TgcScene.xml")]
        public string MeshGirasol {
            get {
                return ((string)(this["MeshGirasol"]));
            }
            set {
                this["MeshGirasol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\mina-TgcScene.xml")]
        public string MeshMina {
            get {
                return ((string)(this["MeshMina"]));
            }
            set {
                this["MeshMina"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\plano-TgcScene.xml")]
        public string MeshPlano {
            get {
                return ((string)(this["MeshPlano"]));
            }
            set {
                this["MeshPlano"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\zombie-TgcScene.xml")]
        public string MeshZombie {
            get {
                return ((string)(this["MeshZombie"]));
            }
            set {
                this["MeshZombie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\caja-TgcScene.xml")]
        public string MeshCaja {
            get {
                return ((string)(this["MeshCaja"]));
            }
            set {
                this["MeshCaja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\Pastofinal-TgcScene.xml")]
        public string MeshPasto {
            get {
                return ((string)(this["MeshPasto"]));
            }
            set {
                this["MeshPasto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Texturas\\skyBox\\")]
        public string TexturasSkyBox {
            get {
                return ((string)(this["TexturasSkyBox"]));
            }
            set {
                this["TexturasSkyBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\Mountain-TgcScene.xml")]
        public string MeshMountain1 {
            get {
                return ((string)(this["MeshMountain1"]));
            }
            set {
                this["MeshMountain1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Texturas\\tierra.jpg")]
        public string TexturaMountain {
            get {
                return ((string)(this["TexturaMountain"]));
            }
            set {
                this["TexturaMountain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\Mountain-TgcScene.xml")]
        public string MeshMountain {
            get {
                return ((string)(this["MeshMountain"]));
            }
            set {
                this["MeshMountain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\CasaDave-TgcScene.xml")]
        public string CasitaDave {
            get {
                return ((string)(this["CasitaDave"]));
            }
            set {
                this["CasitaDave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\Brain-TgcScene.xml")]
        public string MeshBrain {
            get {
                return ((string)(this["MeshBrain"]));
            }
            set {
                this["MeshBrain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\Pea-TgcScene.xml")]
        public string MeshPea {
            get {
                return ((string)(this["MeshPea"]));
            }
            set {
                this["MeshPea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\PastoClaro-TgcScene.xml")]
        public string MeshPastoClaro {
            get {
                return ((string)(this["MeshPastoClaro"]));
            }
            set {
                this["MeshPastoClaro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\PastoMedio-TgcScene.xml")]
        public string MeshPastoMedio {
            get {
                return ((string)(this["MeshPastoMedio"]));
            }
            set {
                this["MeshPastoMedio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objetos\\PastoOscuro-TgcScene.xml")]
        public string MeshPastoOscuro {
            get {
                return ((string)(this["MeshPastoOscuro"]));
            }
            set {
                this["MeshPastoOscuro"] = value;
            }
        }
    }
}
